
USER_ID = "harinijay01"
PAT = "1009f2a845114c6a962a3a4820dfce3e"
APP_ID = "bc12fb78cc454b4fb7c06969a136112a"
WORKFLOW_ID_TEXT = "TEXT"
WORKFLOW_ID_IMAGE = "General"
WORKFLOW_ID_STORY_GPT3 = "image-to-story"
